# Generated by Django 3.1.7 on 2021-03-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txn_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('paytm', 'paytm'), ('paypal', 'paypal')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.TextField(null=True),
        ),
    ]
